package spongecell.guardian.rules.core
 
import spongecell.guardian.model.HDFSDirectory 
import spongecell.guardian.notification.SimpleMailClient 
 
 
/*
 * This rule checks that the number of files in a directory.
 */
dialect "mvel"
rule "1 HDFSDirectory Status Check"
    when
        $hdfsDir1 : HDFSDirectory(statusCheck == HDFSDirectory.FILE_CHECK_UNKNOWN) 
    then
        System.out.println("HDFSDirectory Status Check - statusCheck: " + $hdfsDir1.statusCheck);
end
 
dialect "java"
rule "2 HDFSDirectory Children Check"
    when
        $mailClient : SimpleMailClient(valid == true)
        $hdfsDir : HDFSDirectory(numChildren == 2)               
    then
        System.out.println("Health check passed: Number of children is: " + $hdfsDir.numChildren);
        modify( $mailClient ) { 
        	setSendMail( Boolean.TRUE ),  
        	setValid( Boolean.FALSE)
        };
        System.out.println("Health check passed. SimpleMailClient.sendMail is: " + 
        	$mailClient.sendMail);
end

dialect "mvel"
rule "3 HDFSDirectory Notification Check"
    when
        $sendMailClient : SimpleMailClient(sendMail == Boolean.TRUE)
    then
        System.out.println("Yahoo: " + $sendMailClient.sendMail);
end